### ISSUE TITLE
运行完之后什么也不显示

### ISSUE THREAD

**Issue by 2904202165** [SellWatermelonMan/WeiBoCrawler#1]
![image](https://github.com/user-attachments/assets/a9b33d87-2642-467c-928e-84457e01dfeb)
yun'xing，你好作者，运行完之后什么也不显示，只有一个空的文件，cookie我加进去了呀，是还需要改什么吗

**Comment by zhouyi207** [comment]
可能关键词弄错啦？

**Comment by guobalove** [comment]
刚刚拉下来跑了一下成功了，记得把获取主题内容评论的那两句代码的注释符号删掉
    # 获取主题内容
    wbparser.get_main_body(q, kind)
    # 获取一级评论
    wbparser.get_comments_level_one()
    # 获取二级评论
    wbparser.get_comments_level_two()
